---
defaults:
  actions:
    comment:
#       bot_account: ceph-csi-bot
    merge:
      method: rebase
      rebase_fallback: merge
      strict: smart
      strict_method: rebase
    rebase:
#       bot_account: ceph-csi-bot
pull_request_rules:
  - name: automatic merge PR having ready-to-merge label
    conditions:
      - label!=DNM
      - label=ready-to-merge
    actions:
      merge: {}
      dismiss_reviews: {}
      delete_head_branch: {}
      #hello
